import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import Script from "next/script";
import {Menu, Header, Footer, Layout} from '../components'
import logo from '../public/assets/images/logo.png'

// const inter = Inter({subsets: ['latin']})

export default function Home({Component, pageProps}) {

    return (
        <>
            <Head>
                <title>Ezbets</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                {/*<Script src="@/assets/js/all.min.js"></Script>*/}
                {/*<Script src="../assets/js/bootstrap.bundle.min.js"></Script>*/}
                {/*<Script src="@/assets/js/jquery.min.js"></Script>*/}
                {/*<Script src="@/assets/slick/slick.min.js"></Script>*/}
                {/*<Script src="@/assets/js/wow/wow.min.js"></Script>*/}
                {/*<Script src="@/assets/js/moment.min.js"></Script>*/}
                {/*<Script src="@/assets/js/daterangepicker.min.js"></Script>*/}
                {/*<Script src="../assets/js/apexcharts.min.js"></Script>*/}
                {/*<Script src="../assets/js/chart-custom.min.js"></Script>ßßß*/}
                {/*<Script src="@/assets/js/menu-toggle.min.js"></Script>*/}
                {/*<Script src="@/assets/js/main.js"></Script>*/}
            </Head>
            <>
                <div className="row mx-0">
                    <div className="total-bet">
                        <div className="row mx-0">
                            <div className="col-lg-8 mx-auto">
                                <div className="row mx-0 mb-3 mb-lg-4">
                                    <img className="logo-title mx-auto" src={logo.src}/></div>
                                <div className="card border-0 bg-transparent">
                                    <div className="card-header bg-white pt-0 pb-3 pb-lg-4 border-0 mb-1">
                                        <div className="d-flex justify-content-center">
                                            <div className="title-block px-4 py-2">Total Bet ( Risk Managaemnet)</div>
                                        </div>
                                    </div>
                                    <div className="card-body bg-transparent p-0">
                                        <div className="box py-2 mb-1">
                                            <div className="row mx-0">
                                                <div className="col-8">Username:</div>
                                                <div className="col-4">Wewin247pro</div>
                                            </div>
                                        </div>
                                        <div className="box py-2 mb-1 box-light">
                                            <div className="row mx-0">
                                                <div className="col-8">Login Name:</div>
                                                <div className="col-4">Wewin247pro</div>
                                            </div>
                                        </div>
                                        <div className="box py-2 mb-1">
                                            <div className="row mx-0">
                                                <div className="col-8">Total SH Count:</div>
                                                <div className="col-4">6 ( 6+ 0)</div>
                                            </div>
                                        </div>
                                        <div className="box py-2 mb-1 box-light">
                                            <div className="row mx-0">
                                                <div className="col-8">Total Direct SSMA Count :</div>
                                                <div className="col-4">6 ( 6+ 0)</div>
                                            </div>
                                        </div>
                                        <div className="box py-2 mb-1">
                                            <div className="row mx-0">
                                                <div className="col-8">Total SSMA Count:</div>
                                                <div className="col-4">6 ( 6+ 0)</div>
                                            </div>
                                        </div>
                                        <div className="box py-2 mb-1 box-light">
                                            <div className="row mx-0">
                                                <div className="col-8">Total SMA Count:</div>
                                                <div className="col-4">6 ( 6+ 0)</div>
                                            </div>
                                        </div>
                                        <div className="box py-2 mb-1">
                                            <div className="row mx-0">
                                                <div className="col-8">Total MA Count :</div>
                                                <div className="col-4">6 ( 6+ 0)</div>
                                            </div>
                                        </div>
                                        <div className="box py-2 mb-1 box-light">
                                            <div className="row mx-0">
                                                <div className="col-8">Total Associate Count :</div>
                                                <div className="col-4">6 ( 6+ 0)</div>
                                            </div>
                                        </div>
                                        <div className="box py-2 mb-1 box-light">
                                            <div className="row mx-0">
                                                <div className="col-8">Total Credit Member Count :</div>
                                                <div className="col-4">6 ( 6+ 0)</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        </>
    )
}
